language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: EXxXOqZYQlIgoDdqHvXLDLmUsMoPOOLcr24OAmJemA/+oSiN53ZZlGPQFurwpMn39P6Ngq4uRzK1r+J/m03GEBmp7TdxMaPRjcuSCmuGlcZ/6Ywv9YH+Zb+lovFYpGUEOz1HTnXhO2XeJIdbTLWBWSAsdAvDMyNGW2Kje8cCbp9bE+rTBqodWTVUibUa+ri7e/Rv7GWIoXNl3gXuPTwvidkAv6oueFwgDP7b/8HkSbStTRGA0PTBLHbyaXAOjV5X9t+hz861pHibpXapUR8UmwRN7DvFwkO8+lde55oDJuInQlK/PqIzX3WPYnRLsX+qChxUdLneB3qZMcNqt2M7DrKk5FtHRKS3/QZL8c3oz0ev3y/MzVHxWsHIFXcm3ewu5KyiRkUP/x6rdmGqHCOPDthRmtNbU/mTHTUQAC5R7zS2NHBQgc+iNOa/HyViC7knE+jf+fT7nyP07WDALpFHD701zwm9DxTjUAyHmDAS4Vzbob+IP0H4BLTZxKjUC1vYyRBQlOrsb938i9qjbQKDqHMuo1MYlKtVgBa0lSrKWXDQTFPQgdjkOssijzlfsa7X4V6ntr2K1wNIgQFZptIn8wABOCudJz6Ya3teszDWGxZvPd5jNR3XIeppxq7t1uYq+NmrhBVe1mRlTgqOBks8MZXDJnTx03XGQseNLWU2o0U=
  app: obscure-waters-10676
  strategy: git
