language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: B5Qi98tdVPV+qm/sQQix6Pt0zMkHmY5FTEegUIK31j6EKHrKLuCeyOlSV4USGc5x/7Ek6IcmjHBQtYg4kSU0RjXZm1cHgG6ua4ratSQRo2+joIaRNhFvyTcus6yHPXNhydMDeSRqLXK8GqrPhKhwlxP50PMt7dZG+JAAP1SWVJ16prlkdEsf8D0ccvgmmfL9vHtPZQlfPUiopYiCUsGicXeER5sqcTlV/ab0HZCuj2KDpW/Np3FCH4H5iTz4TOa3GwovjJttK+d41j0AfxiJeyn4fxtCBNgngZ6gObfJHtotX5IllzNnRuzLYixFjGtj434mfo1eI6U2kQZKUsSWzNG765psmkhcA3IcO6JfEQn2XWmFyJuJD4RwbfaD/sMsMLl9WBjKv7DTJPKcw51AStMYC/J66Gig9td/LgLeiModZ0nypj010tte2L8Vm7EjC6yZcsuSX237x2MXLOovItPNsKyQzZ4MOforPuZzs7JxTirbyhuuwvlG1Ae8V73VTfFVOwJfNlRUPVo9goN2jCK17fye4nrJhcLaFwpiSHjTq5L2J5V0j/tKgtzv1LMHYT7v5QHpg78hjuTzno27owyDb8yUpwqQCkW31mlDcCAeQsamKmyEGNi9p22+cIdmoRfrXGeTJlzjfEIFtTVwtu5kzz1dQSDdzZ15WVvELf0=
  app: obscure-waters-10676
  strategy: git
  on:
    all_branches: true
services: mongodb
