language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: W8A7768NDbui6OMTm/DP7FQHvFLFxlha8k98yTBiQECrlr8lb0Oz8ZGMOW1y941S0mr9VnzyP1xZsy53TDxvy7hMMoYfjICKrVXESZ5+s6EZuL8MyuUVN5L65D0DS4jwtfZr/vK215ShqYdUF6YpVFtvdPEO7QL7Vn/pinIRiQsXkshqiWAC800Hq3anHSuCcPrtO3oNC2V2UE/hZSDDDozLxPM1s4WuVcIS9yL9bgq3uiIAM0TGzHQRGmlUUuh3cv9wjiwa7oeXJ7CdmZ0fE2rTMmOORxjp5XXMVfhOM8nafgcpuULDCvTetrDKLwNrhF+PGM04ZTBbHAbL1666dSMTZOeQ7z9En0Z6cXZ/VcqHL8+dXFKKmgW6Q45uno0WOb/Id2se5K5mHZFCanIk4QIdEZEFkHp539cJj0jJjLEr8UUWefyjei/22oVOEeU5n3ZguOKKP/nnL7DWSACGZtNrIbOeIUGW2ryzrV9soc0LvLJ+sCZaAYYH+kA+UbGPvqF0a96MWoLBOUnCzjVv3sro7u8L9/BkJuN6KG+mZgKRG1zqHlovr9eb4NOV86CmoTtn/QbtzgfjQeU2iM7C+QrX/CCCuLN7aTxa771wqGkCk2sr+d78oZCDzrjaElecSZv0A27ux/JSdZnaKFouqP/+zqYAHQbKhPPcACe/Q7U=
  app: shacar
  strategy: git
  on: master
services: mongodb
