language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: xX1fRj4a7tzGxIKfTsKFY/0rqfcAyzHXm1kxIA+9NQmm6Jx0/97qV1vViARw9Lj8Ji2PBUMbzogtQ00G2Bh9NBpeMU7c6UjwrYfKgpAlKLONmnZdCBy48r6+sWJY/8gXxnxI1G+JFbg6b4I3+rkK31OZCuf/mGrg3JwsI6f6DRxdF0mzBBQm2ZBTxdW1WeXn9rqKePDpBe2+3ShOuYXcuM/U1OBvRTm1JaL5rtW51ns8TqEevK1s8syqaUvtf8QJfnXxbcaUImrTrui5p4lnA1iAFfRYBXFsXf6cURV5XED3cYfchVQR+15dZsPFzpcRj4O0mXBADdnVei3ZCEkcJwxcjErIrRTcPllMoeIwS5CkADpIynkUT0TIy7ormzRRD1gq6/jvlarHCpwUDttGbA+XBIH0j/hwfDeZPu4+YGIAfaAH0OGRCs6L9Qe6kC56cbWxIvAGYfX/bpIUwFXqRtgYSKfESfAAylqspdLAWePyRRBqgZDGVHSkmKBw0c913qtcmGwWqD1SgGMMQsLKFCOe+oEA2+9+c+7AEQJZcg25J8QDp/VVK/j5+bHqjlQCaJg0FBUMCzUXjj+40bPpBivNSCpaN4oNsgaAmIF4705bvAxCMQEWX+88KinoQmBQFe/HJpSwsliyhE7J+ZjBQmfxosTNrxhzrD1CidwflFc=
  app: shacar
  strategy: git
  on: master
services: mongodb
